<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [7]:
import numpy as np

numbers = np.array([ 45, 60, 1, 30, 96, 1, 96, 57, 16, 1])
mask = numbers > 30     # mask is now array([False, True, ...])
mask.sum()              # only True subset will be seen, hence added to sum



np.int64(5)

In [8]:
numbers[mask]       # is same as: numbers[numbers>30]

array([45, 60, 96, 96, 57])

In [10]:
numbers[~mask]      # inverts the mask: lists all elements that are NOT in mask

array([ 1, 30,  1, 16,  1])

In [12]:
numbers[(numbers > 1) & (numbers < 60)]     # combined masks: AND  -> gives elements where BOTH masks hold true (overlap region)

array([45, 30, 57, 16])

In [14]:
numbers[(numbers < 2) | (numbers > 60)]     # combined masks: OR   -> gives elements where EITHER ONE OR BOTH masks hold true (union of regions)

array([ 1, 96,  1, 96,  1])

## Exercise 1

|Term   |Brief Description   |
|:---   |:---                |
|Subsetting| to select    |
|Indexing  | selecting an element or a list within a list/array as output, based off of its position in the list/ array  |
|Slicing   | selecting a subset of elements as output based off of its position in the list/array   |
|Masking   | filtering elements based on specified conditions   | 

## Exercise 2

In [61]:
np_array = np.array ([[1,"A"], [3,"C"], [2,"B"], [4, "D"], [5,"E"], [7, "G"], [6,"F"], [8, "H"], [10, "J"], [9, "I"]])
mask1 = np_array[:, 0]
mask1

integers = mask1.astype(int)
print(integers)

remainders = integers%2
print(remainders)

mask2 = remainders ==1      # ask question (use of ==)  -> answer: array([True, False, ...])
mask2



[ 1  3  2  4  5  7  6  8 10  9]
[1 1 0 0 1 1 0 0 0 1]


array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [60]:
final = np_array[mask2,1]
final                       # final        -> array(['A', 'C', 'E', ...])
print(final)                # print(final) -> ['A'  'C'  'E' ...]

['A' 'C' 'E' 'G' 'I']


In [49]:
py_list = [[1, "a"], [2, "b"], [3, "c"], [4, "d"]]
np_array = np.array(py_list)

py_list[3]  # gives [4, 'd']

np_array[3] # gives array(['4', 'd'], dtype='<U21')

array(['4', 'd'], dtype='<U21')

In [50]:
py_list[3][0]

np_array[3,0]       # NumPy should use only one [ ] bracket, separate numbers by comma (it makes a difference to output in some cases)

np.str_('4')

In [24]:
py_list[:3][0]      # gives [1,'a']
np_array[:3][0]     # gives array(['1', 'a'], dtype='<U21') -> output is first data set (0) from range of index 0 to 3
np_array[:3,0]      # gives array(['1', '2', '3'], dtype='<U21')  -> output is first element of all data sets from range of index 0 to 3

array(['1', '2', '3'], dtype='<U21')

In [25]:
x = [1,2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

Appending: adding elements to a python list\
x = [1]\
x = x + [2] same as x += [2]  same as  x.append(2)

For append, must use ( ) instead -> for adding a single new element to end of list


In [38]:
x = [1, 2, 3]
x.append([4, 5, 6])     # cannot write x.append(4, 5, 6) -> list.append() takes exactly 1 argument only. must add [] to interpret a single list [4,5,6] as a single element
x

[1, 2, 3, [4, 5, 6]]

In [31]:
x = [1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [35]:
x = [1, 2, 3]
x.extend('jolly')   # every input is individually segmented as an element: 1, 36, j, k, etc.  -> multiple elements added to end of list
x


[1, 2, 3, 'j', 'o', 'l', 'l', 'y']

In [36]:
x = [1, 2, 3]
x.append('jolly')
x

[1, 2, 3, 'jolly']

## Exercise 3

In [80]:
x = [[66, 50, 57, -1, -1], [92, -1, 88, -1, -1], [75, -1, -1,76, -1], [-1, 51, 87,- 1,- 1], [71, -1, 67, -1, 69]]
np_array = np.array(x)

np_array[np_array > 50] = 1
np_array[np_array ==50] = 0

print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [2]:
import numpy as np
x = [[66, 50, 57, -1, -1], 
     [92, -1, 88, -1, -1], 
     [75, -1, -1,76, -1], 
     [-1, 51, 87,- 1,- 1], 
     [71, -1, 67, -1, 69]]

np_array = np.array(x)

# this isn't necessary!⌄  can do without extra variable
mask1 = np_array > 50  
mask1             # array([[ True, False,  True, False, False], ...
np_array[mask1]   # array([66, 57, 92, 88, 75, 76, 51, 87, 71, 67, 69])

mask2 = np_array[np_array >50]
mask2             # array([66, 57, 92, 88, 75, 76, 51, 87, 71, 67, 69])

array([66, 57, 92, 88, 75, 76, 51, 87, 71, 67, 69])